# Type stubs for tidyrun.serialization

from .api import (
    default_encoders,
    deserialize,
    select_encoder,
    serialize,
)
from .encoders import (
    decode_dataframe_from_parquet,
    decode_dict_from_folder,
    decode_other_from_json,
    decode_pandas_from_hdf5,
    decode_series_from_parquet,
    decode_value_from_pickle,
    encode_dataframe_as_parquet,
    encode_dict_as_folder,
    encode_other_as_json,
    encode_pandas_as_hdf5,
    encode_series_as_parquet,
    encode_value_as_pickle,
    can_encode_series_with_parquet,
    can_encode_with_hdf5,
    can_encode_with_parquet,
    is_dataframe,
    is_json_serializable,
    is_mapping,
    is_pandas_series,
    is_parquet_available,
)
from .lazy_dict import LazyDict
from .types import (
    ChecksumInfo,
    DEFAULT_HDF5_EXTENSION,
    DEFAULT_JSON_EXTENSION,
    DEFAULT_PARQUET_EXTENSION,
    DEFAULT_PICKLE_EXTENSION,
    Deserializer,
    EncoderSpec,
    GoToNextEncoderException,
    Predicate,
    Serializer,
    TidyRunDeserializationError,
    TidyRunSerializationError,
)

__all__ = [
    "DEFAULT_HDF5_EXTENSION",
    "DEFAULT_JSON_EXTENSION",
    "DEFAULT_PARQUET_EXTENSION",
    "DEFAULT_PICKLE_EXTENSION",
    "ChecksumInfo",
    "Deserializer",
    "EncoderSpec",
    "GoToNextEncoderException",
    "LazyDict",
    "Predicate",
    "Serializer",
    "TidyRunDeserializationError",
    "TidyRunSerializationError",
    "can_encode_series_with_parquet",
    "can_encode_with_hdf5",
    "can_encode_with_parquet",
    "decode_dataframe_from_parquet",
    "decode_dict_from_folder",
    "decode_other_from_json",
    "decode_pandas_from_hdf5",
    "decode_series_from_parquet",
    "decode_value_from_pickle",
    "default_encoders",
    "deserialize",
    "encode_dataframe_as_parquet",
    "encode_dict_as_folder",
    "encode_other_as_json",
    "encode_pandas_as_hdf5",
    "encode_series_as_parquet",
    "encode_value_as_pickle",
    "is_dataframe",
    "is_json_serializable",
    "is_mapping",
    "is_pandas_series",
    "is_parquet_available",
    "select_encoder",
    "serialize",
]
